def forecast_data
  {"@context"=>
    ["https://raw.githubusercontent.com/geojson/geojson-ld/master/contexts/geojson-base.jsonld",
     {"wx"=>"https://api.weather.gov/ontology#",
      "s"=>"https://schema.org/",
      "geo"=>"http://www.opengis.net/ont/geosparql#",
      "unit"=>"http://codes.wmo.int/common/unit/",
      "@vocab"=>"https://api.weather.gov/ontology#",
      "geometry"=>{"@id"=>"s:GeoCoordinates", "@type"=>"geo:wktLiteral"},
      "city"=>"s:addressLocality",
      "state"=>"s:addressRegion",
      "distance"=>{"@id"=>"s:Distance", "@type"=>"s:QuantitativeValue"},
      "bearing"=>{"@type"=>"s:QuantitativeValue"},
      "value"=>{"@id"=>"s:value"},
      "unitCode"=>{"@id"=>"s:unitCode", "@type"=>"@id"},
      "forecastOffice"=>{"@type"=>"@id"},
      "forecastGridData"=>{"@type"=>"@id"},
      "publicZone"=>{"@type"=>"@id"},
      "county"=>{"@type"=>"@id"}}],
   "id"=>"https://api.weather.gov/points/32.7766,-96.7968999",
   "type"=>"Feature",
   "geometry"=>{"type"=>"Point", "coordinates"=>[-96.7968999, 32.7766]},
   "properties"=>
    {"@id"=>"https://api.weather.gov/points/32.7766,-96.7968999",
     "@type"=>"wx:Point",
     "cwa"=>"FWD",
     "forecastOffice"=>"https://api.weather.gov/offices/FWD",
     "gridX"=>88,
     "gridY"=>103,
     "forecast"=>"https://api.weather.gov/gridpoints/FWD/88,103/forecast",
     "forecastHourly"=>"https://api.weather.gov/gridpoints/FWD/88,103/forecast/hourly",
     "forecastGridData"=>"https://api.weather.gov/gridpoints/FWD/88,103",
     "observationStations"=>"https://api.weather.gov/gridpoints/FWD/88,103/stations",
     "relativeLocation"=>
      {"type"=>"Feature",
       "geometry"=>{"type"=>"Point", "coordinates"=>[-96.766513, 32.7933329]},
       "properties"=>
        {"city"=>"Dallas",
         "state"=>"TX",
         "distance"=>{"value"=>3395.7587695376956, "unitCode"=>"unit:m"},
         "bearing"=>{"value"=>236, "unitCode"=>"unit:degrees_true"}}},
     "forecastZone"=>"https://api.weather.gov/zones/forecast/TXZ119",
     "county"=>"https://api.weather.gov/zones/county/TXC113",
     "fireWeatherZone"=>"https://api.weather.gov/zones/fire/TXZ119",
     "timeZone"=>"America/Chicago",
     "radarStation"=>"KFWS"}}
end